apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d5x6b4hg0-go 
  janus-idp.io/tekton: d5x6b4hg0-go
  backstage.io/kubernetes-id: d5x6b4hg0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d5x6b4hg0-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  