apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d5x6b4hg0-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d5x6b4hg0-go 
  name: d5x6b4hg0-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d5x6b4hg0-go 
